services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    networks:
      - p3-aau-football
    environment:
      - MONGODB_URI=mongodb://root:root@database:27017/football?authSource=admin
    # Uncomment ports for development:
    #ports:
    #  - "8080:8080"
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - p3-aau-football
    restart: always
    depends_on:
      - backend

  database:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: football
    networks:
      - p3-aau-football
    # Uncomment ports for development:
    #ports:
    #  - "27018:27017"
    volumes:
      - "./db:/data/db:rw"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  p3-aau-football: