services:
  dev-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ./backend:/app
    depends_on:
      dev-database:
        condition: service_healthy
    networks:
      - dev-p3-aau-football
    env_file:
      - ./dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    restart: always

  dev-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
      args:
        BACKEND_URI: http://dev-backend:8080
    volumes:
      - ./frontend:/app
      - ./node_modules_cache:/app/node_modules
    ports:
      - "80:3000"
    networks:
      - dev-p3-aau-football
    environment:
      BACKEND_URI: http://dev-backend:8080
      NODE_ENV: development
    restart: always
    depends_on:
      - dev-backend

  dev-database:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: football
    networks:
      - dev-p3-aau-football
    ports:
      - "27018:27017"
    volumes:
      - "./db:/data/db:rw"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  dev-p3-aau-football:
